## **1. Retrieving the data**

In [135]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [137]:
spyPre_raw = pd.read_csv("edaSpy.csv")
spyPre_raw.head()

,Unnamed: 0,strike,lastPrice,change,openInterest,impliedVolatility,inTheMoney,timeToCall,Close,Volume
0,0,300.0,295.04,0.000000,240.0,2.765628,True,4 days,593.669983,46750300.0
1,1,535.0,55.00,0.000000,1.0,0.544926,True,5 days,590.500000,50032600.0
2,2,540.0,55.04,-0.379997,2.0,0.664554,True,4 days,593.669983,46750300.0
3,3,550.0,46.20,9.780003,1.0,0.564457,True,3 days,595.510010,38226400.0
4,4,560.0,34.84,5.889999,5.0,0.461675,True,3 days,595.510010,38226400.0

In [139]:
spyPre1 = spyPre_raw.drop("Unnamed: 0", axis = 1)
spyPre1.head()

,strike,lastPrice,change,openInterest,impliedVolatility,inTheMoney,timeToCall,Close,Volume
0,300.0,295.04,0.000000,240.0,2.765628,True,4 days,593.669983,46750300.0
1,535.0,55.00,0.000000,1.0,0.544926,True,5 days,590.500000,50032600.0
2,540.0,55.04,-0.379997,2.0,0.664554,True,4 days,593.669983,46750300.0
3,550.0,46.20,9.780003,1.0,0.564457,True,3 days,595.510010,38226400.0
4,560.0,34.84,5.889999,5.0,0.461675,True,3 days,595.510010,38226400.0

In [141]:
spyPre1.timeToCall = spyPre1.timeToCall.str.replace('days', '')
spyPre.timeToCall = spyPre1.timeToCall.astype('int')
spyPre.head()

,strike,lastPrice,change,openInterest,impliedVolatility,inTheMoney,timeToCall,Close,Volume
0,300.0,295.04,0.000000,240.0,2.765628,True,4,593.669983,46750300.0
1,535.0,55.00,0.000000,1.0,0.544926,True,5,590.500000,50032600.0
2,540.0,55.04,-0.379997,2.0,0.664554,True,4,593.669983,46750300.0
3,550.0,46.20,9.780003,1.0,0.564457,True,3,595.510010,38226400.0
4,560.0,34.84,5.889999,5.0,0.461675,True,3,595.510010,38226400.0

In [143]:
spyPre = spyPre.dropna()

spyPre.isnull().sum()

strike               0
lastPrice            0
change               0
openInterest         0
impliedVolatility    0
inTheMoney           0
timeToCall           0
Close                0
Volume               0
dtype: int64

## **2. Splitting the Data into Training and Test Sets**

Before applying PCA, we split our dataset into training and test sets.

In [146]:
from sklearn.model_selection import train_test_split

# Assuming df is your DataFrame and y is your target variable
X = spyPre.drop('lastPrice', axis=1)  # Replace 'target' with your target column name
y = spyPre['lastPrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## **3. Standardize the Data**
We standardize the training data and use the same transformation on the test data.

In [149]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

## **4. Fit PCA on the Training Data**
Fit the PCA model on the scaled training data.

In [130]:
from sklearn.decomposition import PCA

pca = PCA(n_components=0.50)  # We retain 95% of variance
X_train_pca = pca.fit_transform(X_train_scaled)

X_train_pca_

## **5. Transform the Test Data**
We apply the same PCA transformation to the scaled test data.

In [133]:
X_test_pca = pca.transform(X_test_scaled)